### ISSUE TITLE
TRAINING(FINE-TUNING) AND SAVING THE TRAINED MODEL

### ISSUE THREAD

**Issue by tectal** [GhibliField/Multiclass-Text-Classification-using-BERT#1]
FileNotFoundError                         Traceback (most recent call last)
<timed exec> in <module>

c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\torch\serialization.py in save(obj, f, pickle_module, pickle_protocol)
    217         >>> torch.save(x, buffer)
    218     """
--> 219     return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
    220 
    221 

c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\torch\serialization.py in _with_file_like(f, mode, body)
    140             (sys.version_info[0] == 3 and isinstance(f, pathlib.Path)):
    141         new_fd = True
--> 142         f = open(f, mode)
    143     try:
    144         return body(f)

FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/pytorch_model.bin'

**Comment by GhibliField** [comment]
> FileNotFoundError Traceback (most recent call last)
> in
> 
> c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\torch\serialization.py in save(obj, f, pickle_module, pickle_protocol)
> 217 >>> torch.save(x, buffer)
> 218 """
> --> 219 return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
> 220
> 221
> 
> c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\torch\serialization.py in _with_file_like(f, mode, body)
> 140 (sys.version_info[0] == 3 and isinstance(f, pathlib.Path)):
> 141 new_fd = True
> --> 142 f = open(f, mode)
> 143 try:
> 144 return body(f)
> 
> FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/pytorch_model.bin'

You should create a folder named *checkpoints* manually. Sorry for not including in this repo.
